on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ğŸš€ Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies and build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: ğŸ—‚ï¸ Prepare files for deployment
        run: |
          # Crear una carpeta temporal para los archivos a desplegar
          mkdir deployment
          # Copiar el build del frontend
          cp -r frontend/build/* deployment/
          # Copiar el backend
          cp -r backend/* deployment/
          # Puedes ajustar los paths segÃºn tu estructura

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftps4.us.freehostia.com
          username: estavi0
          password: ${{ secrets.FTP_PASSWORD }} 
          server-dir: /rifa.sheerit.com.co/
          local-dir: deployment

